# macOS 10.9
version: 2
defaults: &def
    macos:
      xcode: "8.3.3"
jobs:
  build:
    <<: *def    
    steps:
      - checkout
      # Persist the specified paths (workspace/echo-output) into the workspace for use in downstream job. 
      - persist_to_workspace:
          root: DerivedData
        # Must be relative path from root
          paths:
            - Build
            - Test
            - Logs

      - run: mkdir -p DerivedData

      # Install CocoaPods
#      - run:
#          name: Install CocoaPods
#          command: pod install

      # Build the app and run tests
      - run:
          name: build
          command: xcodebuild -derivedDataPath DerivedData -project XQuit.xcodeproj -scheme XQuit  -destination 'platform=OS X,arch=x86_64'
  deploy:
    <<: *def
    steps:      
      - checkout
      - attach_workspace:
          at: DerivedData

      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: DerivedData/Test
          destination: scan-test-results
      - store_artifacts:
          path: DerivedData/Logs/Test
          destination: scan-logs

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: travis circle
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: travis circle
